Models/ContactosViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace SENSHOP2._1.Models
{
    public class ContactosViewModel
    {
        public string nombre { get; set; }
        public string correo { get; set; }
        public int mensaje  { get; set; }
       
    }

}

Models/ProveedoresViewModel.cs
namespace SENSHOP2._1.Models
{
    public class ProveedoresViewModel
    {
        public string cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string NTelefono { get; set; }
        public string Correo { get; set; }
        public string empresa { get; set; }
    }
}

Controllers/ProveedoresController.cs
using Microsoft.AspNetCore.Mvc;
using SENSHOP2._1.Models;
using SENSHOP2._1.Repositorio;
using System.Security.Cryptography;
using static SENSHOP2._1.Repositorio.RepositorioProveedores;

namespace SENSHOP2._1.Controllers
{
	public class ProveedoresController : Controller
	{

		private readonly IRepositorioProveedores RepoProveer;
		public ProveedoresController(IRepositorioProveedores repoProveer)
		{
			this.RepoProveer = repoProveer;
		}
		public ActionResult RegistrarProveedor(ProveedoresViewModel proveedor) {
		 
		 if (!ModelState.IsValid)
			{
				return View("~/Views/Home/Proveedores.cshtml", proveedor);
			}			RepoProveer.RegistrarProveedor(proveedor);
			return View("~/Views/Home/Proveedores.cshtml");
		}
		public IActionResult Index()
		{
			return View();
			
		}
	}
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using SENSHOP2._1.Models;
using SENSHOP2._1.Repositorio;
using static SENSHOP2._1.Repositorio.RepositorioUsuario;

namespace BYTHEMARKET.Controllers
{
	public class UsuarioController : Controller
	{
		private readonly IRepositorioUsuario repositorioUsuario;
		private readonly IRepositoriohome repohome;

		public UsuarioController(IRepositorioUsuario repositorioUsuario)
		{
			this.repositorioUsuario = repositorioUsuario;
		}
		public IActionResult registrar(RegViewModel user)
		{
            repositorioUsuario.registrarUsuario(user);
            CryptoClass cryptoClasse = new CryptoClass();
            user.cotraseña = cryptoClasse.Encrypt(user.cotraseña);
         
            if (!ModelState.IsValid)
			{
               
                return View("~/Views/SHOP/Tienda.cshtml",user);

			}

           
            return View("~/Views/SHOP/Tienda.cshtml");



        }
		public IActionResult regist (RegViewModel usuario )
		{
			if (!ModelState.IsValid)
			{
                
                return View("~/Views/SHOP/Tienda.cshtml", usuario);
			}
            
            return View();
        }

		[HttpPost]
		public async Task<IActionResult> login(RegViewModel login)
		{
            
            ErrorViewModel error1 = new ErrorViewModel();
			try
			{
				CryptoClass clave = new CryptoClass();
				login.cotraseña = clave.Encrypt(login.cotraseña);
				bool rsp = await repositorioUsuario.ValidarUser(login);
				if (rsp)
				{
                    IEnumerable<ProductoViewModel> productos = repohome.listarProducto();
                    return View("\"~/Views/SHOP/Tienda.cshtml", productos);

				}
				return View("login");
            }
			catch (Exception error)
			{ 
			    error1.RequestId =error.HResult.ToString();
                error1.message = error.HResult.ToString();
            }
			return View("Error", error1);
		}

	}
}

Views/Home/Proveedores.cshtml
@model ProveedoresViewModel
@{
}

<!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
	<link rel="stylesheet" type="text/css" href="~/css/provedor.css" />
    </head>
    <body>

	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-sm-center h-100">
				<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
					<div class="text-center my-5">
						<img src="img/tiendad.jpg" alt="logo" width="100">
					</div>
					
					<div class="card shadow-lg">
						<div class="card-body p-5">
							
							<h1 class="fs-4 card-title fw-bold mb-4"> Añadir Proveedor</h1>
							<form asp-action="RegistrarProveedor" asp-controller="Proveedores" method="post">
								<div class="mb-3">
									<div class="mb-2 w-100">
										<label class="text-muted" for="text">Cedula</label>
									</div>
									<input id="cant" type="text" asp-for="cedula" class="form-control"  required>
									<div class="invalid-feedback">
									</div>
								</div>
								<div class="mb-3">
									<label class="mb-2 text-muted" for="nombre">Nombre</label>
									<input id="idproc" type="text" asp-for="Nombre" class="form-control" value="" required autofocus>
									<div class="invalid-feedback">
									</div>

									<div class="mb-3">
										<div class="mb-2 w-100">
											<label class="text-muted" for="text">Apellido</label>
										</div>
										<input id="cant" type="text" asp-for="Apellido" class="form-control"  required>
										<div class="invalid-feedback">
										</div>
									</div>

									<div class="mb-3">
										<div class="mb-2 w-100">
											<label class="text-muted" for="text">N° de Telefono </label>
										</div>
										<input id="cant" type="text" asp-for="NTelefono" class="form-control"  required>
										<div class="invalid-feedback">
										</div>
									</div>
									<div class="mb-3">
										<div class="mb-2 w-100">
											<label class="text-muted" for="text">Correo electronico</label>
										</div>
										<input id="cant" type="text" asp-for="Correo" class="form-control"  required>
										<div class="invalid-feedback">
										</div>
									</div>

									<div class="mb-3">
										<div class="mb-2 w-100">
											<label class="text-muted" for="text"> empresa al cual pertenece </label>
										</div>
										<input id="cant" type="text" asp-for="empresa" class="form-control"  required>
										<div class="invalid-feedback">
										</div>
									</div>
									<button type="submit" class="btn btn-primary ms-auto">
										Guardar Proveedor
									</button>
							</form>
							
						
							</div>
						</div>
					</div>
				</div>
			</div>
										


	</body>
    </html>

Views/Home/REGCompra.cshtml
@model ProductoViewModel

<!DOCTYPE html>
<html>
<head>
    <title>Registro de Compras</title>
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        <h1>Registro de Compras</h1>
 
            <div class="mb-3">
                <label for="Fecha" class="form-label">Fecha</label>
                <input type="date" class="form-control" name="Fecha" required />
            </div>
            <div class="mb-3">
                <label for="Codigo" class="form-label">Código</label>
                <input type="text" class="form-control" id="codigoProducto" required />
                <button type="button" class="btn btn-primary" onclick="agregarProducto()">Agregar Producto</button>
            </div>
            <div class="mb-3">
                <label for="Proveedor" class="form-label">Proveedor</label>
                <input type="text" class="form-control" name="Proveedor" required />
            </div> 

            <div class="mb-3">
                <label for="Items" class="form-label">Productos</label>
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID Producto</th>
                            <th>Nombre</th>
                            <th>Cantidad</th>
                            <th>Valor por Unidad</th>
                            <th>Subtotal</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
  
                    <tbody id="productosTable">
                        <tr>
                            <td><input type="text" class="form-control" name="ProductoId[]" /></td>
                            <td><input type="text" class="form-control" name="Nombre[]" /></td>
                            <td><input type="number" class="form-control" name="Cantidad[]" onkeydown="calcularSubtotal(event, this)" /></td>
                            <td><input type="number" class="form-control" name="valorPorUnidad[]" /></td>
                            <td><input type="number" class="form-control" name="Subtotal[]" readonly /></td>
                            <td>
                                <button type="button" class="btn btn-danger" onclick="eliminarFila(this)">Eliminar</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

    <button type="submit" id="enviarBtn" class="btn btn-primary">Registrar Compra</button>
      
    </div>

    <script>
        function agregarProducto() {
            var code = $("#codigoProducto").val();
            $.ajax({
                url: '/Producto/ObtenerProductoPorCodigo',
                type: 'GET',
                data: { code: code },
                success: function (producto)

                {
                    var nuevaFila = `
                                        <tr>
                                            <td><input type="text" class="form-control" name="ProductoId[]" value="${producto.code}" readonly /></td>
                                            <td><input type="text" class="form-control"   name="Nombre[]" value="${producto.name}" readonly /></td>
                                            <td><input type="number" class="form-control" name="Cantidad[]" onkeydown="calcularSubtotal(event, this)" /></td>
                                            <td><input type="number" class="form-control" name="Uni[]" value="${producto.p_venta}" readonly /></td>
                                            <td><input type="number" class="form-control" name="Subtotal[]" readonly /></td>
                                            <td><button type="button" class="btn btn-danger" onclick="eliminarFila(this)">Eliminar</button></td>
                                        </tr>
                                            `;  



                    $("#productosTable").append(nuevaFila);
                },
                error: function () {
                    alert("Producto no encontrado.");
                }
            });

        }

        function calcularSubtotal(event, input) {
            if (event.key === 'Enter') {
                event.preventDefault();
                var row = $(input).closest("tr");
                var cantidad = parseFloat(row.find("input[name='Cantidad[]']").val());
                var valorPorUnidad = parseFloat(row.find("input[name='Uni[]']").val());
                var subtotal = (valorPorUnidad * cantidad).toFixed(2);
                row.find("input[name='Subtotal[]']").val(subtotal);
            }
        }

        function eliminarFila(button) {
            var row = button.parentNode.parentNode;
            row.parentNode.removeChild(row);
        }



        

    </script>
    <script>
        document.getElementById("enviarBtn").addEventListener("click", function () {
            const tabla = document.getElementById("productosTable");
            const filas = tabla.querySelectorAll("tbody tr");
            const items = [];// Array

            filas.forEach(fila => {
                const descripcion = fila.querySelector(".Fecha").value;
                const codigo = fila.querySelector(".code").value;
                const descripcion = fila.querySelector(".name").value;
                const cantidad = parseInt(fila.querySelector(".p_venta").value);
                const valor = parseFloat(fila.querySelector(".valor").value);
                const descripcion = fila.querySelector(".Proveedor").value;


                items.push({
                    Fecha: Fecha,
                    Code: code,
                    Nombre: name
                        Cantidad: cantidad,
                    Uni: p_venta,
                    Proveedor: Proveedor,

                });

            });
            fetch("/Compras/RecibirDatos", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(items)
            })
                .then(response => {
                    if (!response.ok) throw new Error("Error en la respuesta del servidor");
                    return response.json();
                })
                .then(data => console.log("Respuesta del servidor:", data))
                .catch(error => console.error("Error al enviar los datos:", error));
        });
    </script>

</body>
</html>

Views/Home/contactos.cshtml
@model ContactosViewModel
@{
}



<!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <title></title>
    </head>
    <body>
        <div>
        <form asp-action="contactos" asp-controller="contactar">
            <nav class="navbar bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                        Contactanos
                    </a>
                </div>
            </nav>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Nombres</label>
                <input type="text" asp-for="nombre" class="form-control" id="exampleFormControlInput1">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Correo Electronico</label>
                <input type="email" asp-for="correo" class="form-control" id="exampleFormControlInput1">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Mensaje </label>
                <textarea class="form-control" asp-for="mensaje" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar ayuda</button>
        </form>
    </div>








</body>
    </html>

Views/Home/login.cshtml
@model SENSHOP2._1.Models.RegViewModel
@{
	ViewData["Title"] = "login";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Muhamad Nauval Azhar">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<meta name="description" content="This is a login page template based on Bootstrap 5">
	<title>Bootstrap 5 Login Page</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-sm-center h-100">
				<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
					<div class="text-center my-5">
						<img src="img/tiendad.jpg" alt="logo" width="100">
					</div>
					<div class="card shadow-lg">
						<div class="card-body p-5">
							<h1 class="fs-4 card-title fw-bold mb-4">Login</h1>
							<form asp-action="login" asp-controller="Usuario" method="post">
								<div class="mb-3">
									<label class="mb-2 text-muted" for="nombre">Nombre</label>
									<input asp-for="name" id="nombre" type="text" class="form-control" name="nombre" value="" required autofocus>
									<div class="invalid-feedback">
										Name is required
									</div>

								<div class="mb-3 m-2">
									<div class="mb-2 w-100">
											<input asp-for="cotraseña" id="password" type="password" class="form-control" name="password" required>
										<label class="text-muted" for="password">Contraseña</label>
										<a asp-controller="home" asp-action="olvido" >
											¿Olvido su contraseña?
										</a>
									</div>
									
									<div class="invalid-feedback">
										Contraseña requerida
									</div>
								</div>
									@if (TempData["Error"] != null)
									{
										<div style=" color: red;">
											@TempData["Error"]
										</div>
									}
								<div class="d-flex align-items-center">
									<div class="form-check">
										<input type="checkbox" name="remember" id="remember" class="form-check-input">
										<label for="remember" class="form-check-label">Mostrar contraseña</label>
									</div>
									<button type="submit" class="btn btn-primary ms-auto">
										Ingresar
									</button>
									
									
								</div>
							</form>
						</div>
						<div class="card-footer py-3 border-0">
							<div class="text-center">
								¿No tiene cuenta? <a asp-controller="home" asp-action="registrar" class="text-dark">Crear una</a>
							</div>
						</div>
					</div>
					<div class="text-center mt-5 text-muted">
						Copyright &copy; 2017-2021 &mdash; Your Company
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="js/login.js"></script>
</body>
</html>

Views/Home/registrar.cshtml
@model RegViewModel
@{
}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Muhamad Nauval Azhar">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<meta name="description" content="This is a login page template based on Bootstrap 5">
	<title>Bootstrap 5 Login Page</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-sm-center h-100">
				<div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
					<div class="text-center my-5">
						<img src="img/tiendad.jpg" alt="logo" width="100">
					</div>
					<div class="card shadow-lg">
						<div class="card-body p-5">
							<h1 class="fs-4 card-title fw-bold mb-4">Registrar</h1>
							<form asp-action="registrar" asp-controller="Usuario" method="post">
								<div asp-validation-summary="ModelOnly" class="text-danger"></div>
								<div class="mb-3">
									<label asp-for="n_identficacion" class="mb-2 text-muted" for="identificacion">N° de identificacion</label>
									<input type="text" class="form-control" asp-for="n_identficacion">

									<div>
										<span asp-validation-for="n_identficacion" class="text-danger"></span>
									</div>
								</div>

								<div class="mb-3">
									<label asp-for ="name" class="mb-2 text-muted" for="email">Nombre</label>
									<input id="nombre" type="text" class="form-control" asp-for="name" >
									<div>
										<span asp-validation-for="name" class="text-danger"></span>
									</div>
								</div>

								<div class="mb-3">
									<label asp-for="apellido" class="mb-2 text-muted" for="apellido">Apellidos</label>
									<input id="apellido" type="text" class="form-control" asp-for="apellido" >
									<div>
										<span asp-validation-for="apellido" class="text-danger"></span>
									</div>
								</div>
								<div>
									
								
									<select asp-items="Html.GetEnumSelectList<Tiposexo>()" class="form-select" id="sexo" ></select>
								</div>

								<div class="mb-3">
									<label asp-for="fecha" class="form-label">Fecha de nacimiento</label>
									<input type="date" class="form-control" asp-for="fecha">
									<div>
										<span asp-validation-for="fecha" class="text-danger"></span>
									</div>

								</div>

								<div class="mb-3">
									<label asp-for="correo" class="mb-2 text-muted" for="email">Correo electronico</label>
									<input id="correo" type="email" class="form-control" asp-for="correo" name="correo" >
									<div >
										<span asp-validation-for="correo" class="text-danger"></span>
									</div>
								</div>
								<div class="mb-3">
									<label asp-for=cotraseña class="mb-2 text-muted" for="cotraseña">Contraseña</label>
									<input id="contraseña" type="password" class="form-control" asp-for="cotraseña" name="cotraseña">
									<div >
										
											<span asp-validation-for="cotraseña" class="text-danger"></span>
			
									</div>

								</div>
								
								@if (TempData["error"] != null)
								{
									<div style="color:red;">
										@TempData["error"]
									</div>
								}
								<div class="align-items-center d-flex">
									<button type="submit" class="btn btn-primary ms-auto">
										Register
									</button>



								</div>
								<div class="align-items-lg-end flex-sm-nowrap">
								
								</div>


							</form>

						</div>

					</div>
					<div class="card-footer py-3 border-0">
						<div class="text-center">
							Already have an account? <a href="index.html" class="text-dark">Login</a>
						</div>
					</div>
				</div>
				<div class="text-center mt-5 text-muted">
					Copyright &copy; 2017-2021 &mdash; Your Company
				</div>
			</div>
		</div>
		</div>
	</section>

	<script src="js/login.js"></script>
</body>
</html>