Models/ProductoViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SENSHOP2._1.Models
{
    public class ProductoViewModel
    {
        public string code { get; set; }
        public string name { get; set; }
        public string p_venta { get; set; }
        public string Uni { get; set; }
        public string descripsionE { get; set; }
        public string descripsionP { get; set; }
        public string Marca { get; set; }

        [DataType(DataType.Upload)]
        public IFormFile sl_img { get; set; }
        public string urlimagen { get; set; }
        public DateTime Fecha { get; set; }

    }

   
}

Controllers/CArController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using Microsoft.IdentityModel.Tokens;
using SENSHOP2._1.Models;
using SENSHOP2._1.Repositorio;
using System.Collections.Concurrent;
using System.Net.Http.Headers;
using System.Reflection.Metadata.Ecma335;
using static SENSHOP2._1.Models.CarritoViewModel;
using static SENSHOP2._1.Repositorio.RepositorioProducto;
using static SENSHOP2._1.Repositorio.RepositorioCarrito;

namespace SENSHOP2._1.Controllers
{
    public class CArController : Controller
    {
        private readonly IRepositorioCarro _carritoservicio;
        private readonly IRepositorioProducto _repositorioProducto;
        public CArController(IRepositorioCarro carritoservicio, IRepositorioProducto repositorioProducto)
        {
            _carritoservicio = carritoservicio;
            _repositorioProducto = repositorioProducto;
        }
        public IActionResult agregar(int id, int cantidad)
        {
            var Detalle = _repositorioProducto.Selectcar(id);
            if (Detalle != null)
            {

                _carritoservicio.AGitemcarro(Detalle, cantidad);
            }
            var carritoItems = _carritoservicio.listarItemsCarro();
            return View("~/Views/SHOP/CarrodeC.cshtml", carritoItems);
        }
     
        public IActionResult elimina(int productoID) {
        
               _carritoservicio.eliminaritemcarro(productoID);
            var carroitem = _carritoservicio.listarItemsCarro();
            return View("~/Views/SHOP/CarrodeC.cshtml", carroitem);
        }
        public IActionResult actualizar(int productID, int cantidad) {

            if (cantidad < 1) {

                return BadRequest("La cantida minima debe de ser almenos de 1.");


            }
            _carritoservicio.actualizarItemCarro(productID, cantidad);
            var carroitem = _carritoservicio.listarItemsCarro();
            return View("~/Views/SHOP/CarrodeC.cshtml", carroitem);
        
        }

     public IActionResult tienda()
        {
            return View("~/Views/SHOP/Tienda.cshtml");
        }
          
         
        public IActionResult CarrodeC()
        {
            return View("~/Views/SHOP/CarrodeC.cshtml");
        }
    }
}

Controllers/FacturaController.cs
using iText.Kernel.Events;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using Microsoft.AspNetCore.Mvc;
using SENSHOP2._1.Models;
using SENSHOP2._1.PDF;
using static SENSHOP2._1.Repositorio.RepositorioFactura;
using static SENSHOP2._1.Repositorio.RepositorioPDF2;

namespace SENSHOP2._1.Controllers
{
    public class FacturaController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IRepositorioFactura _repositorioFactura;

        public FacturaController(IConfiguration configuration, IRepositorioFactura Repofac)
        {
            _configuration = configuration;
            _repositorioFactura = Repofac;
        }

        public IActionResult Facturar(ProductoViewModel producto)
        {
            MemoryStream stream = new MemoryStream();
            PdfWriter writer = new PdfWriter(stream);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);
            pdf.AddEventHandler(PdfDocumentEvent.END_PAGE, new footer(document));

            // Añadir encabezado de la factura
            document.Add(new Paragraph("FACTURA")
                .SetFontSize(24)
                .SetBold()
                .SetTextAlignment(TextAlignment.CENTER));

            // Añadir detalles del vendedor
            document.Add(new Paragraph("Nombre del Vendedor: Tu Empresa")
                .SetFontSize(12)
                .SetTextAlignment(TextAlignment.LEFT));
            document.Add(new Paragraph("Dirección: Calle Falsa 123")
                .SetFontSize(12)
                .SetTextAlignment(TextAlignment.LEFT));
            document.Add(new Paragraph("Teléfono: +123 456 7890")
                .SetFontSize(12)
                .SetTextAlignment(TextAlignment.LEFT));
            document.Add(new Paragraph("Fecha: " + DateTime.Now.ToString("dd/MM/yyyy"))
                .SetFontSize(12)
                .SetTextAlignment(TextAlignment.RIGHT));

            // Espacio entre secciones
            document.Add(new Paragraph("\n\n"));

            // Añadir detalles de productos
            var facs = _repositorioFactura.GenerarFactura(new ProductoViewModel());

            foreach (var p in facs)
            {
                document.Add(new Paragraph($"Código del producto: {p.code}")
                    .SetFontSize(12)
                    .SetTextAlignment(TextAlignment.LEFT));
               ;
                document.Add(new Paragraph($"Precio: {p.p_venta}")
                    .SetFontSize(12)
                    .SetTextAlignment(TextAlignment.LEFT));
                document.Add(new Paragraph($"Descripción del producto: {p.descripsionE}")
                    .SetFontSize(12)
                    .SetTextAlignment(TextAlignment.LEFT));
                document.Add(new Paragraph($"Fecha: {DateTime.Now.ToString("dd/MM/yyyy")}")
                    .SetFontSize(12)
                    .SetTextAlignment(TextAlignment.LEFT));
                document.Add(new Paragraph("\n"));
            }

            document.Close();

            byte[] pdfBytes = stream.ToArray();
            Response.Headers.Add("Content-Disposition", "inline; filename=Factura.pdf");
            return File(pdfBytes, "application/pdf");
        }
    }


}

Controllers/InventarioController.cs
using Microsoft.AspNetCore.Mvc;
using SENSHOP2._1.Models;
using SENSHOP2._1.Repositorio;
using System.ComponentModel.DataAnnotations;
using System.Data;
using Dapper;
using Microsoft.Data.SqlClient;

namespace SENSHOP2._1.Controllers
{
    public class InventarioController : Controller
    {

        private readonly IRepositoriohome repohome;
        public InventarioController(IRepositoriohome repositoriohome)
        {
            this.repohome = repositoriohome;
        }
        public IActionResult produc()
        {
            IEnumerable<ProductoViewModel> productos =repohome.listarProducto();
            return View(productos);
        }


        public IActionResult Tienda()
        {
            IEnumerable<ProductoViewModel> productos = repohome.listarProducto();
            return View("~/Views/SHOP/Tienda.cshtml", productos);

        }

    }
}
    

Controllers/PDF2Controller.cs
using iText.Kernel.Events;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using Microsoft.AspNetCore.Mvc;
using SENSHOP2._1.Models;
using SENSHOP2._1.PDF;
using static SENSHOP2._1.Repositorio.PDFRepositorio1;
using static SENSHOP2._1.Repositorio.RepositorioPDF2;

namespace SENSHOP2._1.Controllers
{
    public class PDF2Controller : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IRepositorioPDF_2 _repositorioPDF2;
        private readonly IRepositorioPDF1 _repositorioPDF1;

        public PDF2Controller(IConfiguration configuration, IRepositorioPDF_2 repositorioPDF2, IRepositorioPDF1 repositorioPDF1)
        {
            _configuration = configuration;
            _repositorioPDF2 = repositorioPDF2;
            _repositorioPDF1 = repositorioPDF1; 
        }

        public IActionResult ListadoProductosPdf2(ProductoViewModel producto)
        {
            MemoryStream stream = new MemoryStream();
            PdfWriter writer = new PdfWriter(stream);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);
            pdf.AddEventHandler(PdfDocumentEvent.END_PAGE, new footer(document));

            document.Add(new Paragraph("Productos Registrados")
                .SetFontSize(18)
                .SetBold()
                .SetTextAlignment(TextAlignment.CENTER));

            Table table = new Table(5, true);
            table.AddHeaderCell("Codigo");
            table.AddHeaderCell("Nombre del producto");
            table.AddHeaderCell("Precio en venta");
            table.AddHeaderCell("Descripcion del producto");
            table.AddHeaderCell("Unidades");
        

            ProductoViewModel model = new ProductoViewModel();
            var pdf2 = _repositorioPDF2.HacerPDF2(model);
            foreach (var p in pdf2)
            {
                table.AddCell(p.code);
                table.AddCell(p.name);
                table.AddCell(p.p_venta);
                table.AddCell(p.descripsionE);
                table.AddCell(p.Uni);
                
            
            }

            document.Add(table);
            document.Close();

            byte[] pdfBytes = stream.ToArray();
            Response.Headers.Add("Content-Disposition", "inline; filename=Productos Registrados.pdf");
            return File(pdfBytes, "application/pdf");
        }
        
       


        public IActionResult proveedoreslist(ProveedoresViewModel proveer)
        {
            MemoryStream stream = new MemoryStream();
            PdfWriter writer = new PdfWriter(stream);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);
            pdf.AddEventHandler(PdfDocumentEvent.END_PAGE, new footer(document));

            document.Add(new Paragraph("Listados de Proveedores")
                .SetFontSize(18)
                .SetBold()
                .SetTextAlignment(TextAlignment.CENTER));

            Table table = new Table(5, true);
            table.AddHeaderCell("Cedula");
            table.AddHeaderCell("Nombres");
            table.AddHeaderCell("Apellidos");
            table.AddHeaderCell("Numero de telefeno");
            table.AddHeaderCell("Empresa");


            ProveedoresViewModel model = new ProveedoresViewModel();
            var pdf2 = _repositorioPDF1.proveedorespdf(model);
            foreach (var p in pdf2)
            {

                table.AddCell(p.Nombre);
                table.AddCell(p.Apellido);
                table.AddCell(p.NTelefono);
                table.AddCell(p.empresa);


            }

            document.Add(table);
            document.Close();

            byte[] pdfBytes = stream.ToArray();
            Response.Headers.Add("Content-Disposition", "inline; filename=Listado de productos.pdf");
            return File(pdfBytes, "application/pdf");
        }
    }
}

Controllers/PDFController.cs
using iText.Kernel.Events;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using Microsoft.AspNetCore.Components.Routing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SENSHOP2._1.Models;
using SENSHOP2._1.PDF;
using static SENSHOP2._1.Repositorio.PDFRepositorio1;
using static SENSHOP2._1.Repositorio.RepositorioPDF2;

namespace SENSHOP2._1.Controllers
{
    public class PDFController : Controller
    {
		


	}
}

Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SENSHOP2._1.Models;
using SENSHOP2._1.Repositorio;
using System.Collections.Generic;
using System.Reflection.PortableExecutable;
using static SENSHOP2._1.Models.CarritoViewModel;
using static SENSHOP2._1.Repositorio.RepositorioProducto;



namespace SENSHOP2._1.Controllers
{
    public class ProductoController : Controller
    {
		
		public readonly IRepositorioProducto repoproducto;
        private readonly ProductoViewModel _context;

        public ProductoController(IRepositorioProducto repoHome)
        {
            this.repoproducto = repoHome;
        }
        public async Task<IActionResult> producto(ProductoViewModel model)
        {
            try
            {
                if (model.sl_img != null && model.sl_img.Length > 0)
                {

                    var extension = Path.GetExtension(model.sl_img.FileName);
                    var nuevoname = Guid.NewGuid().ToString() + extension;
                    var filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Produimag", nuevoname);
                    using (var stream = new FileStream(filepath, FileMode.Create))
                    {
                        await model.sl_img.CopyToAsync(stream);
                    }

                    model.urlimagen = "./produimag/" + nuevoname;
                    repoproducto.producto(model);

                }

            }
            catch
            {

            }


            return View("~/Views/SHOP/producto.cshtml");
        }
        [HttpGet]
        public string Mensaje()
        {
            return "mensaje Back sino crees";
        }

        [HttpGet]
        public JsonResult detalle(int id)
        {

            ProductoViewModel detalle = repoproducto.detalleproc(id);
            return Json(detalle);
        }
        [HttpPost]
        public async Task<IActionResult> Borrar(int id)
        {
            await repoproducto.BorrarProducto(id);
            return View("~/Views/SHOP/Gracias.cshtml");

        }

		[HttpGet]
		public async Task<IActionResult> ObtenerProductoPorCodigo(string code) 
        { var producto = await repoproducto.ObtenerProductoPorCodigo(code);                                  
            if (producto == null) 
            { return NotFound(); } 
            return Json(producto);
        }
	}

}

Views/SHOP/AdministradorTienda.cshtml
@model IEnumerable<ProductoViewModel>
@{
    ViewData["Title"] = "Pagina de productos";
}


<!DOCTYPE html>
<html>
<head>
    <title>SENSHOP</title>
    <link rel="stylesheet" href="~/css/diseñotiendar.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<body>
    <form asp-action="Buscar" asp-controller="Producto" method="post">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SENSHOP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-action="login" asp-controller="home">Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="producto" asp-controller="home">Añadir</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="CarrodeC" asp-controller="CAr">Carro</a>
                        </li>
                    </ul>
                    <i class="fas fa-shopping-cart"></i>
                    <input class="form-control me-2" type="search" placeholder="Buscar productos..." aria-label="Buscar">
                    <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i> Buscar</button>
                </div>
            </div>
        </nav>
    </form>

    <div id="carouselExampleFade" class="carousel slide carousel-fade">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/img/SENSHOP (1).png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/img/SENSHOP2.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/img/SENSHOP (2).png" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

   


    <div class="modal fade" id="modalprod" tabindex="-1" aria-labelledby="modalprodLabel" aria-hidden="true">
        <div class=" modal-dialog">
            <div class=" modal-content">
                <div class=" modal-header">
                    <h5 class="  modal-title" id="modalpdLabel">Producto</h5>
                    <button type="button" class="btn-close btnna" data-bs-dismiss="modal" arial-label="close"></button>

                </div>
                <div class=" modal-body" id="modalBody">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> Cerrar</button>
                </div>
            </div>
        </div>

    </div>
    <form asp-action="PDF" asp-controller="Home" method="post">
        <button class="btn btn-outline-success" type="submit">PDF</button>
    </form>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(document).on('click', '.btnna', function () {
                $('#modalprod').modal('show');
                var productoid = this.id;
                $.ajax({
                    url: '/Producto/detalle',
                    type: 'GET',
                    data: { id: productoid },
                    success: function (data) {
                        const contenido = `<div>

                                                               <img width= 472px height="300px"  src="${data.urlimagen}"/>
                                                               <h3> <strong>${data.name} </strong></h3>
                                                                                       <p style="color:#28b463">  <strong> $: ${data.p_venta} </strong> </p>
                                                                                       <p>  <strong> ${data.descripsionE}</strong></p>
                                                                             <p> <strong>Marca:</strong> ${data.Marca} </P>
                                                                      <p> ${data.descripsionP}</p>

                                                    </div>`;
                        $('#modalBody').html(contenido);

                    },
                    Error: function (error) {
                        $('#modalBody').html('Error al cargar los datos');
                        console.error('error en la llamada AJAX:', Error);
                    }
                });
            });

        });



    </script>

</body>
<br />
<br />
<br />
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col">
                <h4>CONTACTANOS</h4>
                <ul>
                    <li><a href="home/contactos">Contactos</a></li>
                    <li><a href="#">our services</a></li>
                    <li><a href="#">privacy policy</a></li>
                    <li><a href="#">affiliate program</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>get help</h4>
                <ul>
                    <li><a asp-action="kks" asp-controller="Home">COMPRAS</a></li>
                    <li><a href="#">shipping</a></li>
                    <li><a href="#">returns</a></li>
                    <li><a href="#">order status</a></li>
                    <li><a href="#">payment options</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>online shop</h4>
                <ul>
                    <li><a href="#">watch</a></li>
                    <li><a href="#">bag</a></li>
                    <li><a href="#">shoes</a></li>
                    <li><a href="#">dress</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>

<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</html>

Views/SHOP/CarrodeC.cshtml
@model List<CarritoViewModel.carroitem>
@{
    ViewData["Title"] = "Carrito de Compras";
    decimal total = Model.Sum(item => (item?.producto?.p_venta ?? 0) * (item?.cantidad ?? 0));
}

   
   
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <style>
        .comprar-container {
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <h2>
        Carrito
    </h2>
    @if (Model.Count == 0)
    {
        <p>No tienes productos en tu carrito chaval</p>
        <a href="@Url.Action("Tienda", "Inventario")" class="btn btn-primary">Ver productos</a>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    
                    <th>Producto</th>
                    <th>Descripsion</th>
                    <th>Cantidad</th>
                    <th>Precio unitario</th>
                    <th>Subtotal</th>
                    <th>Acciones</th>

                </tr>
            </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.producto.name</td>
                        <td>@item.producto.descripsionE</td>
                   
                    <td>

                            <form asp-action="actualizar" asp-controller="CAr" method="post" style="display:inline;">

                                <input type="hidden" name="productID" value="@item.producto.code" />
                                <input type="number" name="cantidad" value="@item.cantidad" min="1" class="form-control" style="width: 60px;" />
                                <button type="submit" class="btn btn-sm btn-secondary">Actualizar</button>

                            </form>
                        <td>@item.producto.p_venta.ToString("C2")</td>
                        <td>@((item.producto.p_venta * item.cantidad).ToString("C2"))</td>
                        <td>
                            <form asp-action="elimina" asp-controller="CAr" method="post" style="display:inline;">
                                <input type="hidden" name="productoID" value="@item.producto.code" />
                                <input type="submit" class="btn btn-danger  btn-sm" value="Eliminar" />

                            </form>

                            <div class="comprar-container">
                                <form asp-action="Borrar" asp-controller="Producto" method="post">
                                    <input type="hidden" name="id" value="@item.producto.code" />
                                    <button type="submit" class="btn btn-success">
                                        Comprar
                                    </button>
                                </form>
                            </div>
                        </td>

                    </td>
          
                </tr>
                    
            }

        </tbody>

        <tfoot>
            <tr>
                <td colspan="4" class="text-right"><strong>Total:</strong> </td>
                <td>@total.ToString("C2")</td>

                
            </tr>
        </tfoot>
        
        </table>
        <div class="text-right">
            <a href="@Url.Action("Tienda", "Inventario")" class="btn btn-success">Volver a la Tienda</a>

            
        </div>
       
          
       

    }
</body>
</html>

Views/SHOP/Gracias.cshtml
<!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
    </head>
    <body>
    <div class="card-footer py-3 border-0">
        <div class="text-center">
            Volver A la tienada <a asp-controller="Home" asp-action="Tienda" class="text-dark">Volver</a>
        </div>
    </div>
    <img src="~/img/SENSHOP (3).png" class="img-fluid" alt="...">
    <div class="card-footer py-3 border-0">
        <div class="text-center">
            Factura <a asp-controller="Factura" asp-action="Facturar" class="text-dark">Obtener factura</a>
        </div>
    </div>
    </body>
    </html>

Views/SHOP/PDF.cshtml
@{
    ViewData["Title"] = "Listado de Personas";
}

<h2>Listado de Personas</h2>
<p>
    Haga click en el siguiente enlace para generar el documento
</p>
<form asp-action="proveedoreslist" asp-controller="PDF2" method="post">
    <button class="btn btn-outline-success" type="submit">PDF</button>
</form>
<form asp-action="ListadoProductosPdf2" asp-controller="PDF2" method="post">
    <button class="btn btn-outline-success" type="submit">PDF2</button>
</form>
<form asp-action="Listadousers" asp-controller="PDFUSER" method="post">
    <button class="btn btn-outline-success" type="submit">PDF3</button>
</form>
]

Views/SHOP/producto.cshtml
@model ProductoViewModel
@{
}

<!DOCTYPE html>
    <html>
    <head>
        <title>
        <meta charset="utf-8">
        <meta name="author" content="Muhamad Nauval Azhar">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="This is a login page template based on Bootstrap 5">
        <title>Bootstrap 5 Login Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    </title>
    </head>
    <body>
        <h5 class="text-center"> PRODUCTOS</h5>
    <form asp-action="producto" asp-controller="Producto" enctype="multipart/form-data">
        <div class="form-group">
            <label for="code">Codigo</label>
            <input type="number" asp-for="code" class="form-control" id="code"  placeholder="Ingrese el codigo">
           
        </div>
        <div class="form-group">
            <label for="name">Nombre</label>
            <input type="text"  asp-for="name" class="form-control" id="name" placeholder="Su nombre">
        </div>
      
        <div class="mb-3">
            <label for="" class="form-label">Descrpcion Pequeña</label>
            <input type="text" asp-for="descripsionP" class="form-control" id="exampleFormControlInput1">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Descripcion Extensa</label>
            <textarea class="form-control" asp-for="descripsionE" id="exampleFormControlTextarea1" rows="3"></textarea>
            <small id="pequeño" class="form-text text-muted">Definer maximo de caracteres</small>

        </div>
       
        <div class="form-group">
            <label for="name">Precio Venta</label>
            <input type="text" asp-for="p_venta" class="form-control" id="exampleInputPassword1" placeholder="">
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect2">Estado</label>
            <select multiple class="form-control" id="exampleFormControlSelect2">
                <option>Activo</option>
                <option>Inactivo</option>
               
            </select>
        </div>
        <div class="form-group">
            <label for="name">Marca</label>
            <input type="text" asp-for="Marca" class="form-control" id="exampleInputPassword1" placeholder="">
        </div>
        <div class="form-group">
            <label for="name">Unidades</label>
            <input type="text"asp-for="Uni" class="form-control" id="exampleInputPassword1" placeholder="">
        </div>
        <div class="form-group">
            <label for="name">Seleccionar imagen</label>
            <input type="file" class="form-control" asp-for=" sl_img" id="exampleInputPassword1" placeholder="">
        </div>

        <button contextmenu="center" type="submit" class="btn btn-primary">Guardar</button>
        
    </form>
    <form action="Tienda" method="post"><button type="submit" class="btn btn-primary">Salir</button></form>
   
</body>

    </html>
    

Views/SHOP/quieneres.cshtml
@model RegViewModel

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingreso a la Tienda</title>
</head>
<body>
    <h1>Bienvenido a la Tienda</h1>
    <p>Por favor, selecciona tu rol:</p>
    <form asp-action="quieneres" method="post">
        <input type="radio" id="admin" name="Role" value="admin">
        <label for="admin">Administrador</label><br>
        <input type="radio" id="user" name="Role" value="user">
        <label for="user">Usuario</label><br><br>
        <input type="submit" value="Ingresar">
    </form>

    @if (ViewBag.Message != null)
    {
        <p>@ViewBag.Message</p>
    }
</body>
</html>